name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
         #Install npm dependencies, cache them correctly
      # and run all Cypress tests
          # runTests: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # we have already installed all dependencies above
          # install: false
          # Cypress tests and config file are in "e2e" folder
          working-directory: e2e
      
      # Upload screenshots on failure
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: always()  # This step always runs
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload videos
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: always()  # This step always runs
        with:
          name: cypress-videos
          path: cypress/videos
