name: E2E
on: push
jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # or specify the Node.js version you need

    - name: Install Dependencies
      run: npm ci

    - name: Build (if present)
      run: npm run build --if-present

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: dist